services:
  - type: web
    name: youtube-search-worker
    env: node
    plan: free
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/opt/render/.cache/puppeteer/chrome/linux-140.0.7339.80/chrome-linux64/chrome"
